name: Backend Lambda Zip Deploy S3
on:
    push:
      branches:
        - main
  
jobs:
    example-job:
            runs-on: ubuntu-latest
            steps:
              - name: Configure AWS CLI
                run: |
                  mkdir -p ~/.aws/
                  echo "$super_secret" > ~/.aws/credentials
                env:
                  super_secret: ${{ secrets.AWS_CONFIG1 }}
        
              - name: Show AWS credentials 
                run: cat ~/.aws/credentials
        
              - name: List AWS profiles
                run: aws configure list-profiles
        
              - name: List S3 buckets
                run: aws s3 ls --region eu-central-1 --profile techstarter
    deploy:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # To fetch the current commit and its parent (so we can compare)
  
      - name: Setup AWS CLI
        run: |
          mkdir -p ~/.aws/
          echo "$super_secret" > ~/.aws/credentials
        env:
         super_secret: ${{ secrets.AWS_CONFIG1 }}

      - name: Show AWS credentials 
        run: cat ~/.aws/credentials

      - name: List AWS profiles
        run: aws configure list-profiles

      - name: List S3 buckets
        run: aws s3 ls --region eu-central-1 --profile techstarter
    
      - name: Deploy Modified Files
        run: |
       
          S3_BUCKET=s3://tf-backend-abschlussproject/ 
          S3_KEY=login.zip
          LAMBDA_FUNCTION_NAME=login-google
          # Download the existing zip from S3
          aws s3 cp s3://$S3_BUCKET/$S3_KEY login.zip
      
     